### ISSUE TITLE
Show code with asterisks

### ISSUE THREAD

**Issue by javiersantos** [glomadrian/material-code-input#5]
Is there any way to show asterisks instead of the original characters?

Thanks!

**Comment by glomadrian** [comment]
not yet, but is a good feature, i will try to add in the next release

**Comment by FloatingGhost** [comment]
Wait, I'll add a public method to do the same.

**Comment by FloatingGhost** [comment]
Ok re-done - Now you can add a linear layout for a button/showpassword checkbox
