### ISSUE TITLE
Not able to prepopulated setcode  

### ISSUE THREAD

**Issue by Sushil21** [glomadrian/material-code-input#9]
Hi,

i am not able to prepopulated setcode.so please give me solution.basically i  want to show prepopulated code to CodeInput.

Thanks

**Comment by pranaysharma** [comment]
maybe emulate keypresses by calling .onKeyUp.
.onKeyDown() worked for deleting the characters. Though its a hack. Better would be to clone the repo and make a function to pre-set the 'character'  variable I think.

**Comment by mihirjoshi21** [comment]
Added setCode(String). Clone from my fork or wait for merge.

**Comment by Shruti1310** [comment]
Thanks for the help @mihirjoshi21

**Comment by Murtowski** [comment]
When are you about to merge this [feature](https://github.com/glomadrian/material-code-input/blob/master/codeinputlib/src/main/java/com/github/glomadrian/codeinputlib/CodeInput.java)? @mihirjoshi21 
I'm using compile 'com.github.glomadrian:CodeInput:1.1@aar'
and it is still no there
